sudo: required
services:
 - docker

before_install:
 - docker build -t cstockdill/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cstockdill/react-test npm test

after_success:
  - docker build -t cstockdill/multi-client ./client
  - docker build -t cstockdill/multi-nginx ./nginx
  - docker build -t cstockdill/multi-server ./server
  - docker build -t cstockdill/multi-worker ./worker
  # login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # now push images
  - docker push cstockdill/multi-client
  - docker push cstockdill/multi-nginx
  - docker push cstockdill/multi-server
  - docker push cstockdill/multi-worker
    
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  name: "multi-docker2"
  env: "MultiDocker2-env"
  bucket_name: "elasticbeanstalk-us-west-2-950262647039"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY
